spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Cars_Sales?createDatabaseIfNotExist=true
    username: hassan
    password: 123hassan
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

